### PR TITLE
v2v: Fix list drivers on missing ISO domain

### PR DESCRIPTION
**Pull request by matobet**
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1467856

### CODE REVIEW

**Comment by matobet** [comment]
@miq-bot assign @gmcculloug

**Comment by matobet** [comment]
@miq-bot add_label fine/yes

**Comment by gmcculloug** [comment]
@matobet Test failures are unrelated.  Something @tinaafitz and I need to work on.

Also, you do not need to approve your own PRs, it is assume the author wants it merged unless it is marked as `wip`.

**Comment by chrispy1** [comment]
@miq-bot add_label blocker

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit 598813772ad9218fa966ce71d4a5edccb965d9d9
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Mon Jul 10 12:34:49 2017 -0400

    Merge pull request #139 from matobet/master
    
    v2v: Fix list drivers on missing ISO domain
    (cherry picked from commit 3cf974ee6a5275f20943918b65f4ceb2856cf3e8)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1469228
```

**Pull request merged**
