### PR TITLE
[Changelog] Update for Hammer-4

### PR DESCRIPTION
**Pull request by JPrause**
[skip ci]

### CODE REVIEW

**Comment by JPrause** [comment]
@miq-bot add_label documentation

**Comment by JPrause** [comment]
@miq-bot add_label hammer/yes

**Comment by JPrause** [comment]
@carbonin as time permits, can you review merge. We need this for today's build.

**Comment by JPrause** [comment]
@tinaafitz as time permits, can you review merge. We need this for today's build.

**Comment by JPrause** [comment]
:+1: thanks @tinaafitz

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit bc182604196c9debc4c16755ca6469e3fdbd0c98
Author: tina <tina.fitzgerald2@gmail.com>
Date:   Wed Mar 27 08:58:11 2019 -0400

    Merge pull request #520 from JPrause/hammer4_cl
    
    [Changelog] Update for Hammer-4
    
    (cherry picked from commit 3ce28cf9e67bfd8b3934fd68b7cd1577a6731b0c)
```

**Pull request merged**
