### PR TITLE
Add openstack cloud tenant events

### PR DESCRIPTION
**Pull request by tzumainn**
https://bugzilla.redhat.com/show_bug.cgi?id=1411112

### CODE REVIEW

**Comment by tzumainn** [comment]
@miq-bot add_label bug

**Comment by gmcculloug** [comment]
@lfu Please review

**Comment by lfu** [comment]
@tzumainn Please make sure the steps in [Creating a Pull Request for enhancements to ManageIQ Automate Domain](http://talk.manageiq.org/t/creating-a-pull-request-for-enhancements-to-manageiq-automate-domain/1041) has been followed to export the automate modeling.
Otherwise it looks good to me.

**Comment by tzumainn** [comment]
@lfu Yep!  I followed the path in Option 2, and also verified that catching the relevant events caused a refresh to trigger.

**Pull request merged**
