### PR TITLE
Added active provisions to quota count.

### PR DESCRIPTION
**Pull request by billfitzgerald0120**
Updated method and test.
https://bugzilla.redhat.com/show_bug.cgi?id=1497983

Added log messages for counts and quota type.
Sample log messages below: 

<AEMethod used> Quota Used: {:cpu=>373, :memory=>922780434432, :vms=>141, :storage=>9111136632832, :provisioned_storage=>10033917067264}

<AEMethod used> Quota active_provisions_by_tenant: {:cpu=>1, :memory=>1073741824, :vms=>1, :storage=>44023414784, :provisioned_storage=>0}
<AEMethod used> Quota Totals: {:cpu=>374, :memory=>923854176256, :vms=>142, :storage=>9155160047616, :provisioned_storage=>10033917067264}

<AEMethod used> Quota Used: {:cpu=>1, :memory=>1073741824, :vms=>1, :storage=>8589934592, :provisioned_storage=>9663676416}
<AEMethod used> Quota active_provisions_by_group: {:cpu=>1, :memory=>1073741824, :vms=>1, :storage=>44023414784, :provisioned_storage=>0}
<AEMethod used> Quota Totals: {:cpu=>2, :memory=>2147483648, :vms=>2, :storage=>52613349376, :provisioned_storage=>9663676416}

<AEMethod used> Quota Used: {:cpu=>1, :memory=>1073741824, :vms=>1, :storage=>8589934592, :provisioned_storage=>9663676416}
<AEMethod used> Quota active_provisions_by_owner: {:cpu=>0, :memory=>0, :vms=>0, :storage=>0, :provisioned_storage=>0}
<AEMethod used> Quota Totals: {:cpu=>1, :memory=>1073741824, :vms=>1, :storage=>8589934592, :provisioned_storage=>9663676416}

@miq-bot add_label bug, fine/yes

### CODE REVIEW

**Comment by billfitzgerald0120** [comment]
@miq-bot assign @gmcculloug

**Comment by gmcculloug** [comment]
@billfitzgerald0120 Please review failing spec.

**Comment by billfitzgerald0120** [comment]
Removed old spec which was causing travis to fail.

**Comment by simaishi** [comment]
@billfitzgerald0120 This was refactored in https://github.com/ManageIQ/manageiq-content/pull/191, which is not in Fine branch. Should PR 191 be backported to Fine?  If not, please create a separate PR for Fine branch.

**Comment by billfitzgerald0120** [comment]
@simaishi I don't think we need to backport https://github.com/ManageIQ/manageiq-content/pull/191.  This PR needs to be backported.

**Comment by simaishi** [comment]
@billfitzgerald0120 Then, please create a PR for Fine branch. This PR can't be backported as is due to the refactoring.

**Comment by billfitzgerald0120** [comment]
@simaishi We do need both of these back ported.

More detail here: 
https://bugzilla.redhat.com/show_bug.cgi?id=1489507

Thanks 
Billy

**Comment by simaishi** [comment]
@billfitzgerald0120 please make sure all needed PRs are marked as `fine/yes`. Thanks!

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit 0db92735f28c731ff45652ec8ddc1164cb243165
Author: Madhu Kanoor <mkanoor@redhat.com>
Date:   Fri Oct 13 10:05:54 2017 -0400

    Merge pull request #196 from billfitzgerald0120/used_new_active_provisions
    
    Added active provisions to quota count.
    (cherry picked from commit a38ebc9efffa62117cf717ca89ce168501736c53)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1489507
```

**Comment by simaishi** [comment]
@billfitzgerald0120 Can you take a look at Travis failure? 
https://travis-ci.org/ManageIQ/manageiq-content/builds/304801822

There was a conflict backporting to Fine branch in https://github.com/ManageIQ/manageiq-content/pull/196/files#diff-9c5e8f4a07d3caa797737be3a823473eL22, so probably spec needs to be updated somewhere else?

**Comment by billfitzgerald0120** [comment]
@simaishi We need this one back ported too.   https://github.com/ManageIQ/manageiq-content/pull/132    I added the fine/yes label to it.

**Pull request merged**
