### PR TITLE
Remove use of iteritems method

### PR DESCRIPTION
**Pull request by syncrou**
Brings this module inline with requirements for Python 3

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1736116

### CODE REVIEW

**Comment by syncrou** [comment]
@miq-bot add_label bug

@miq-bot assign @carbonin

**Comment by syncrou** [comment]
- cc @tinaafitz

**Comment by syncrou** [comment]
@billfitzgerald0120 would you be able to test this on a RHEL 8 appliance?

**Comment by carbonin** [comment]
Will this cause a problem with the ManageIQ appliance which is still running CentOS 7 (and thus python2)?

**Comment by syncrou** [comment]
Closing. Per @carbonin's comment. Will need to validate all changes are backwards compatible with Python 2 and 3.

**Comment by syncrou** [comment]
Closed in favor of #557 also test for backwards compatibility with Python 2

**Pull request closed without merging**
