### PR TITLE
AzureStack events for targeted refresh

### PR DESCRIPTION
**Pull request by mancabizjak**
In this commit we add automate class and instances corresponding to AzureStack provider events. All the events added here trigger targeted refresh.

#### Links
* Related PR in [ManageIQ/manageiq-providers-azure_stack/pull/16](https://github.com/ManageIQ/manageiq-providers-azure_stack/pull/16) in which we implement `event_target_parser` for processing these events.

@miq-bot add_label enhancement
@miq-bot assign @gmcculloug 

/cc  @Ladas @agrare

### CODE REVIEW

**Comment by gmcculloug** [comment]
@mancabizjak Thanks for the contribution.

One question about the path, where is the naming `Azure_Stack` coming from?  I would expect this to be camel case `AzureStack` which would be consistent with the other EMS events classes: https://github.com/ManageIQ/manageiq-content/tree/master/content/automate/ManageIQ/System/Event/EmsEvent

**Comment by mancabizjak** [comment]
@gmcculloug I share your concern about the consistency in the naming of `Azure_Stack` automate class. The underscore case comes from the current implementation of `EventParser` in AzureStack provider, where we use `AZURE_STACK` source (see [event_parser#L9](https://github.com/ManageIQ/manageiq-providers-azure_stack/blob/9222a1af071b2a59eaec325b720a5ce54e801fdb/app/models/manageiq/providers/azure_stack/cloud_manager/event_parser.rb#L9)), which was autogenerated from the provider name. 

Renaming the class without updating `EventParser` in the provider would give us something like this:

```bash
[----] I, [2019-10-11T13:07:25.811650 #27587:2b28c779a5fc]  INFO -- : Following Relationship [miqaedb:/System/Event/EmsEvent/AZURE_STACK/Administrative_Microsoft.Compute_virtualMachines_write_Succeeded#create]
[----] E, [2019-10-11T13:07:25.867143 #27587:2b28c779a5fc] ERROR -- : Class [System/Event/EmsEvent/AZURE_STACK] not found in MiqAeDatastore
[----] I, [2019-10-11T13:07:25.867176 #27587:2b28c779a5fc]  INFO -- : Followed  Relationship [miqaedb:/System/Event/EmsEvent/AZURE_STACK/Administrative_Microsoft.Compute_virtualMachines_write_Succeeded#create]

```

Personally, I would prefer to name the class `AzureStack` as well, and don't mind making the change in the provider (@agrare does that make sense)?

**Comment by agrare** [comment]
Yeah that works for me, we can make it AZURESTACK, that would be consistent with other providers

**Comment by mancabizjak** [comment]
Okay, done - I renamed the automate class to `AzureStack` and made the change in [ManageIQ/manageiq-providers-azure_stack/pull/17](https://github.com/ManageIQ/manageiq-providers-azure_stack/pull/17). I think we're good to go :+1:

**Pull request merged**
