### PR TITLE
v2v: Fix confusing message in WaitForImport state

### PR DESCRIPTION
**Pull request by matobet**
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1467866

### CODE REVIEW

**Comment by matobet** [comment]
@miq-bot assign @gmcculloug

**Comment by matobet** [comment]
@miq-bot add_label fine/yes

**Comment by chrispy1** [comment]
@miq-bot add_label blocker

**Comment by gmcculloug** [comment]
Unrelated test failures, working with @tinaafitz on that.  This change is good to merge.

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit 5ad4a0271165cabe7a8c18bea8c01b7e5428b0c3
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Mon Jul 10 12:04:26 2017 -0400

    Merge pull request #140 from matobet/v2v-texts
    
    v2v: Fix confusing message in WaitForImport state
    (cherry picked from commit 478d65ffa9e875bef2a1f2ddc59ca946d5e8a88b)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1469226
```

**Pull request merged**
