### PR TITLE
[WIP]Refactoring cloud vm retirement email vm_retirement_emails method

### PR DESCRIPTION
**Pull request by pkomanek**
Purpose or Intent
---------------------

Refactoring `Cloud/VM/Retirement/Email.class/__methods__/vm_retirement_emails.rb` method with adding a new spec. This PR is based on the issue bellow.

Links
-------------------
#8 

@miq-bot add_label refactoring

### CODE REVIEW

**Comment by billfitzgerald0120** [comment]
@pkomanek I modified this method in https://github.com/ManageIQ/manageiq-content/pull/349

**Comment by mkanoor** [comment]
@billfitzgerald0120 Can you confirm this is a deprecated method and we don't have to convert it.

**Comment by billfitzgerald0120** [comment]
@pkomanek @mkanoor This method is being deprecated in PR https://github.com/ManageIQ/manageiq-content/pull/349/files

We should close this one.

**Comment by billfitzgerald0120** [comment]
@mkanoor I am deprecating this method in PR mentioned above.  Can you close it ?

**Pull request closed without merging**
