### PR TITLE
Run rake clean_yaml_files with a newer Psych version

### PR DESCRIPTION
**Pull request by Fryguy**
Newer versions of psych do not emit trailing whitespace, and if left in
place the clean_yaml_spec.rb fails.

cc @simaishi

### CODE REVIEW

**Comment by Fryguy** [comment]
This will have to go on jansa too, but will not backport clean

**Comment by Fryguy** [comment]
This actually seems more related to the libyaml version installed.  See https://github.com/yaml/libyaml/pull/186

**Comment by djberg96** [comment]
I wondered why it was doing that, interesting.

**Comment by Fryguy** [comment]
Yeah I can't quite figure this out one...maybe travis changed something in their images?

**Comment by chessbyte** [comment]
@Fryguy if you want this merged, needs a rebase

**Comment by Fryguy** [comment]
I can't figure it out, unfortunately...going to close for now.

**Comment by simaishi** [comment]
@Fryguy @djberg96 I looked into this a bit (as I keep getting daily email from Travis regarding jansa build failing!).

When I run spec locally for 'master', test fails (and this PR is the fix for it). But when the spec runs in Travis, the test passes. 

Local run uses:
```
psych version: 3.2.0
libyaml version: [0, 2, 5]
```
Travis run uses:
```
psych version: 3.2.0
libyaml version: [0, 1, 6]
```

libyaml 0.2.5 is the version with the whitespace change and that's included in psych 3.2. I'm not sure how to figure out where libyaml 0.1.6 is coming from in Travis run. Can you help?

**Comment by djberg96** [comment]
@simaishi I'm tinkering to see if I can force Travis to blow up via https://github.com/ManageIQ/manageiq-content/pull/675.

**Comment by simaishi** [comment]
Oh I see... that's where 0.1.6 is coming from. Travis run from #675:

```
libyaml-dev is already the newest version (0.1.6-3)
```

**Pull request closed without merging**
