### PR TITLE
[V2V] Remove PowerOn and CheckPoweredOn states

### PR DESCRIPTION
**Pull request by fdupont-redhat**
The state machine is being ported to InfraConversionJob.
This PR is the counterpart of ManageIQ/manageiq#19241.

A side effect of removing the PowerOn and CheckPoweredOn methods, is that the /Transformation/Infrastructure tree is not needed anymore. So, the PR removes it too.

__WIP__ because it's also used by Transformation Cleanup state machine.

RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1748100
Depends on ManageIQ/manageiq#19241
Built on #573

### CODE REVIEW

**Comment by fdupont-redhat** [comment]
@miq-bot add-label transformation, refactoring, ivanchuk/yes
@miq-bot add-reviewer @gmcculloug
@miq-bot add-reviewer @tinaafitz

**Comment by fdupont-redhat** [comment]
@miq-bot add-label wip

**Comment by fdupont-redhat** [comment]
Dependent PR has been merged.

**Comment by fdupont-redhat** [comment]
@miq-bot remove-label wip

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit b55b85a9f61c9b3ca98e629f33982828a495a648
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Wed Sep 11 09:50:04 2019 -0400

    Merge pull request #575 from fdupont-redhat/v2v_state_machine_power_on
    
    [V2V] Remove PowerOn and CheckPoweredOn states
    
    (cherry picked from commit 91ced52383b676fd9b8b892fcf2c18a4e5570a7e)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1768539
```

**Comment by simaishi** [comment]
The backport reverted

```
commit 33f1d27ab14660f2e1f38fc562da61a56a4ab931
Author: Satoe Imaishi <simaishi@redhat.com>
Date:   Tue Dec 3 11:11:31 2019 -0500

    Revert "Merge pull request #575 from fdupont-redhat/v2v_state_machine_power_on"

    This reverts commit b55b85a9f61c9b3ca98e629f33982828a495a648.

    https://bugzilla.redhat.com/show_bug.cgi?id=1768539
```

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit dbfdbf844b3a1d6de544ba7aa1fd5674af7efc9e
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Wed Sep 11 09:50:04 2019 -0400

    Merge pull request #575 from fdupont-redhat/v2v_state_machine_power_on

    [V2V] Remove PowerOn and CheckPoweredOn states

    (cherry picked from commit 91ced52383b676fd9b8b892fcf2c18a4e5570a7e)

    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1768539
```

**Pull request merged**
