### PR TITLE
[V2V] Remove RestoreVmAttributes state

### PR DESCRIPTION
**Pull request by fdupont-redhat**
The state machine is being ported to InfraConversionJob.
This PR is the counterpart of ManageIQ/manageiq#19240.

RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1748075
Depends on ManageIQ/manageiq#19240
Built on #572

### CODE REVIEW

**Comment by fdupont-redhat** [comment]
@miq-bot add-label transformation, refactoring, ivanchuk/yes
@miq-bot add-reviewer @gmcculloug
@miq-bot add-reviewer @tinaafitz

**Comment by fdupont-redhat** [comment]
Dependent PR has been merged.

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit 0cf513156c03f434b00ba7785a0769cc84f11b05
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Wed Sep 11 09:48:55 2019 -0400

    Merge pull request #573 from fdupont-redhat/v2v_state_machine_restore_vm_attributes
    
    [V2V] Remove RestoreVmAttributes state
    
    (cherry picked from commit 519e0a9197d4d7492b5c220b206d8146a59eff4c)
    
    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1768524
```

**Comment by simaishi** [comment]
The backport reverted

```
commit 07d176c485af199d3c463fbf69b01f9048b3909e
Author: Satoe Imaishi <simaishi@redhat.com>
Date:   Tue Dec 3 11:11:52 2019 -0500

    Revert "Merge pull request #573 from fdupont-redhat/v2v_state_machine_restore_vm_attributes"

    This reverts commit 0cf513156c03f434b00ba7785a0769cc84f11b05.

    https://bugzilla.redhat.com/show_bug.cgi?id=1768524
```

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit bad9069f794a685aacf8da18d2f0f52713495feb
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Wed Sep 11 09:48:55 2019 -0400

    Merge pull request #573 from fdupont-redhat/v2v_state_machine_restore_vm_attributes

    [V2V] Remove RestoreVmAttributes state

    (cherry picked from commit 519e0a9197d4d7492b5c220b206d8146a59eff4c)

    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1768524
```

**Pull request merged**
