### PR TITLE
[V2V] Remove Ansible Playbook content

### PR DESCRIPTION
**Pull request by fdupont-redhat**
The state machine is being ported to InfraConversionJob.
This PR is the counterpart of ManageIQ/manageiq#19242.

A side effect of implementing the new transitions for post-migration Ansible playbook is that the /Transformation/Ansible tree is not needed anymore, as well as the Ansible state machine. So, the PR removes it too.

WIP because it depends on #575

RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1748121
Depends on ManageIQ/manageiq#19242
Built on #575

### CODE REVIEW

**Comment by fdupont-redhat** [comment]
@miq-bot add-label transformation, refactoring, ivanchuk/yes, wip
@miq-bot add-reviewer @gmcculloug
@miq-bot add-reviewer @tinaafitz

**Comment by fdupont-redhat** [comment]
Dependent PR has been merged.

**Comment by fdupont-redhat** [comment]
@miq-bot remove-label wip

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit 815e036022f76f9ab7adfb1b6bf3128f4843bdf8
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Wed Sep 11 09:50:22 2019 -0400

    Merge pull request #576 from fdupont-redhat/v2v_state_machine_post_migration_ansible_playbook
    
    [V2V] Remove Ansible Playbook content
    
    (cherry picked from commit 21ab4fcda2182d67b50285753cd11db0718f579c)
    
    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1768527
```

**Comment by simaishi** [comment]
The backport reverted

```
commit 4e43e40c0759c67d47a027a9a943b39b91b367ac
Author: Satoe Imaishi <simaishi@redhat.com>
Date:   Tue Dec 3 11:11:16 2019 -0500

    Revert "Merge pull request #576 from fdupont-redhat/v2v_state_machine_post_migration_ansible_playbook"

    This reverts commit 815e036022f76f9ab7adfb1b6bf3128f4843bdf8.

    https://bugzilla.redhat.com/show_bug.cgi?id=1768527
```

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit c813798329b4db9e3175819829e8c37367d25a56
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Wed Sep 11 09:50:22 2019 -0400

    Merge pull request #576 from fdupont-redhat/v2v_state_machine_post_migration_ansible_playbook

    [V2V] Remove Ansible Playbook content

    (cherry picked from commit 21ab4fcda2182d67b50285753cd11db0718f579c)

    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1768527
```

**Pull request merged**
