### PR TITLE
Removed ConfigurationManagement namespace. 

### PR DESCRIPTION
**Pull request by billfitzgerald0120**
Removed ConfigurationManagement namespace and all classes, instances and methods.

ConfigurationManagement namespace has been deprecated and replaced by AutomationManagement namespace.

### CODE REVIEW

**Comment by billfitzgerald0120** [comment]
@miq-bot add_label technical debt

**Comment by billfitzgerald0120** [comment]
@mkanoor Please review

**Comment by billfitzgerald0120** [comment]
@miq-bot remove_label unmergeable

**Comment by gmcculloug** [comment]
@mkanoor @tinaafitz This looks ready to me.  Please approve or provide additional comments.

**Pull request merged**
