### PR TITLE
handle volume snapshot status changes

### PR DESCRIPTION
**Pull request by AlexanderZagaynov**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1561937
Сompanion of https://github.com/ManageIQ/manageiq-providers-amazon/pull/439

### CODE REVIEW

**Comment by gmcculloug** [comment]
@lfu Please review

**Comment by lfu** [comment]
Normally the yaml file is named after the event instance name. Is there any reason that they are different in this PR?
Please follow the steps in [Creating a Pull Request for enhancements to ManageIQ Automate Domain](http://talk.manageiq.org/t/creating-a-pull-request-for-enhancements-to-manageiq-automate-domain/1041).

**Comment by AlexanderZagaynov** [comment]
@lfu that instruction won't work:
```
irb(main):001:0> MiqAeDomain.where(:name => 'ManageIQ').first.update_attributes(:system => false)
PostgreSQLAdapter#log_after_checkout, connection_pool: size: 5, connections: 1, in use: 1, waiting_in_queue: 0
  MiqAeDomain Load (0.4ms)  SELECT  "miq_ae_namespaces".* FROM "miq_ae_namespaces" WHERE "miq_ae_namespaces"."parent_id" IS NULL AND ("miq_ae_namespaces"."name" != '$') AND "miq_ae_namespaces"."name" = $1 ORDER BY "miq_ae_namespaces"."id" ASC LIMIT $2  [["name", "ManageIQ"], ["LIMIT", 1]]
  MiqAeDomain Inst Including Associations (32.0ms - 1rows)
   (0.1ms)  BEGIN
   (0.1ms)  ROLLBACK
ActiveModel::UnknownAttributeError: unknown attribute 'system' for MiqAeDomain.
```

**Comment by lfu** [comment]
@AlexanderZagaynov The talk post can't be modified. Any update would show up as comments. The last comment mentions the command that works with the latest DB:
```
MiqAeDomain.find_by_name(‘ManageIQ’).update_attributes(:source => ‘user’)
```

**Comment by AlexanderZagaynov** [comment]
@lfu yeah, I did that. Please review.

**Pull request merged**
