### PR TITLE
Add handler for compute.instance.update

### PR DESCRIPTION
**Pull request by Ladas**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1666238

### CODE REVIEW

**Comment by Ladas** [comment]
@miq-bot add_label hammer/yes

**Comment by bthurber** [comment]
Associated BZ:  https://bugzilla.redhat.com/show_bug.cgi?id=1666238

**Comment by Ladas** [comment]
@miq-bot add_label blocker

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit b75bf4853953e5eade40a92cdfeea753fbc2d43e
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Tue Jan 15 08:36:56 2019 -0500

    Merge pull request #497 from Ladas/add_handler_for_compute_instance_update
    
    Add handler for compute.instance.update
    
    (cherry picked from commit 5cfd7ccc45556e9e552820da2159f39bcc663ee3)
    
    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1666238
```

**Pull request merged**
