### PR TITLE
Auto approval for instance resize operation.

### PR DESCRIPTION
**Pull request by billfitzgerald0120**
This will set auto approval for instance resize/reconfiguration.

Depends on core PR ManageIQ/manageiq#16044
Depends on UI PR https://github.com/ManageIQ/manageiq-ui-classic/pull/2241

### CODE REVIEW

**Comment by billfitzgerald0120** [comment]
@miq-bot add_label enhancement
@miq-bot assign @gmcculloug

**Comment by billfitzgerald0120** [comment]
@tinaafitz please review

**Comment by gmcculloug** [comment]
@tinaafitz Please review.

@billfitzgerald0120 Can this be un-wipped?

**Comment by tinaafitz** [comment]
@billfitzgerald0120 Looks good.

**Pull request merged**
