### PR TITLE
Change exceeds message in log to warn type.

### PR DESCRIPTION
**Pull request by billfitzgerald0120**
https://bugzilla.redhat.com/show_bug.cgi?id=1383732

@miq-bot add_label bug, fine/yes. euwe/yes

### CODE REVIEW

**Comment by billfitzgerald0120** [comment]
@miq-bot add_label fine/yes, euwe/yes

**Comment by billfitzgerald0120** [comment]
@tinaafitz 
Please Review

**Comment by billfitzgerald0120** [comment]
@tinaafitz 
Please Review

**Comment by tinaafitz** [comment]
@billfitzgerald0120 Looks good.
@mkanoor Please review.

**Comment by simaishi** [comment]
@billfitzgerald0120 Half the files are conflicting during cherry-pick. Can you please create an Euwe PR for this?

**Comment by billfitzgerald0120** [comment]
@simaishi 
We are not going to backport this to Euwe.

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit 76c00db8c70117a3305e09f79106f4b43a367991
Author: Madhu Kanoor <mkanoor@redhat.com>
Date:   Mon May 8 14:06:34 2017 -0400

    Merge pull request #104 from billfitzgerald0120/log_cleanup2
    
    Change exceeds message in log to warn type.
    (cherry picked from commit 5330cb9f558da906d6bd2ed94f9ff07658defa0b)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1459243
```

**Pull request merged**
