### PR TITLE
v2v: Rephrase ISO driver selection

### PR DESCRIPTION
**Pull request by matobet**
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1467858

### CODE REVIEW

**Comment by matobet** [comment]
@miq-bot assign @tinaafitz

**Comment by matobet** [comment]
@miq-bot add_label fine/yes

**Comment by gmcculloug** [comment]
@matobet You need to update the test to match the updated string.  It also looks like different items are coming back for the iso_images.

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit aabe6e5b9bca089369c7cc2deb8f03a66cafd29c
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Thu Aug 10 11:04:43 2017 -0400

    Merge pull request #169 from matobet/master
    
    v2v: Rephrase ISO driver selection
    (cherry picked from commit 3ecab134beeab427d2d97b5c80457244f0d2ac65)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1480586
```

**Pull request merged**
