### PR TITLE
Remove createfolder event handler since it is now handled by MiqVimBrokerWorker

### PR DESCRIPTION
**Pull request by agrare**
As of https://github.com/ManageIQ/manageiq/pull/14460 we will now do a targeted refresh of any new folder so we don't need the event handler to kick off a refresh for the `CreateFolder` event.

### CODE REVIEW

**Comment by gmcculloug** [comment]
@agrare Should this be `Fine/no`?

**Comment by agrare** [comment]
@gmcculloug that depends on if https://github.com/ManageIQ/manageiq/pull/14460 gets marked for `fine/yes`

**Comment by agrare** [comment]
Euwe BZ https://bugzilla.redhat.com/show_bug.cgi?id=1445318

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit 5a3e8794f53b95e0155e06aa9e6f48a8e371f918
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Mon Apr 24 13:45:40 2017 -0400

    Merge pull request #100 from agrare/bz_1378984_new_folder_targeted_refresh
    
    Remove createfolder event handler since it is now handled by MiqVimBrokerWorker
    (cherry picked from commit bc925cd28553330e5b7cade15dceab15ad356947)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1445311
```

**Comment by simaishi** [comment]
Euwe backport (to manageiq repo) details:

```
$ git log -1
commit 42388d22f33bcb9371385db33680b2a05aa1cfa8
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Mon Apr 24 13:45:40 2017 -0400

    Merge pull request #100 from agrare/bz_1378984_new_folder_targeted_refresh
    
    Remove createfolder event handler since it is now handled by MiqVimBrokerWorker
    (cherry picked from commit bc925cd28553330e5b7cade15dceab15ad356947)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1445318
```

**Pull request merged**
