### PR TITLE
Changelog 65

### PR DESCRIPTION
**Pull request by mfeifer**
5 PRs total
5 in changelog

[skip ci]

### CODE REVIEW

**Comment by mfeifer** [comment]
@miq-bot add_label wip

**Comment by mfeifer** [comment]
@miq-bot add_label documentation

**Comment by mfeifer** [comment]
@miq-bot remove_label wip

**Comment by gmcculloug** [comment]
Sorry @mfeifer I missed setting the milestone on PR https://github.com/ManageIQ/manageiq-content/pull/144.  Please add it to the list.

**Pull request merged**
