### PR TITLE
[WIP] Automate - Rename ConfigurationManagement to AutomationManagement.

### PR DESCRIPTION
**Pull request by billfitzgerald0120**
Update wait_for_completion method.
    
See https://github.com/ManageIQ/manageiq/pull/13630

### CODE REVIEW

**Comment by billfitzgerald0120** [comment]
@tinaafitz 
Please Review

**Comment by billfitzgerald0120** [comment]
@tinaafitz 
Please Review

**Comment by tinaafitz** [comment]
@billfitzgerald0120 Looks good.

**Comment by mkanoor** [comment]
This PR has been closed because of backward compatibility issues. A new namespace was created in PR #33

**Pull request closed without merging**
