### PR TITLE
Do targeted refresh based on Openstack events.

### PR DESCRIPTION
**Pull request by mansam**
@ladas Does this make sense to you?

### CODE REVIEW

**Comment by gmcculloug** [comment]
@lfu Please review

**Comment by lfu** [comment]
The changes look good. 

Please follow the steps in [Creating a Pull Request for enhancements to ManageIQ Automate Domain](http://talk.manageiq.org/t/creating-a-pull-request-for-enhancements-to-manageiq-automate-domain/1041) to keep the YAML files format consistent.

**Comment by gmcculloug** [comment]
@mansam Did you follow the process @lfu mentioned here: https://github.com/ManageIQ/manageiq-content/pull/184#issuecomment-328193803 ?

Just trying to validate, thanks.

**Comment by mansam** [comment]
@gmcculloug Hi Greg, yes.

**Pull request merged**
