### PR TITLE
Add notifications for finish_retirement.

### PR DESCRIPTION
**Pull request by tinaafitz**
https://bugzilla.redhat.com/show_bug.cgi?id=1446466

### CODE REVIEW

**Comment by tinaafitz** [comment]
@miq-bot add-label blocker, bug, services, fine/yes

**Comment by tinaafitz** [comment]
Related PR:
https://github.com/ManageIQ/manageiq/pull/14955

**Comment by gmcculloug** [comment]
@tinaafitz Please review test failures.

**Comment by tinaafitz** [comment]
@gmcculloug Fixed test failures.

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit 54111016d389c8a3b0c98d256617c2c699615438
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Tue May 2 13:54:15 2017 -0400

    Merge pull request #106 from tinaafitz/add_notification_to_finish_retirement
    
    Add notifications for finish_retirement.
    (cherry picked from commit 4b97013913f288f3a99b1133005ecbc70a4f76cb)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1447367
```

**Pull request merged**
