### PR TITLE
[V2] Remove ApplyRightSize state

### PR DESCRIPTION
**Pull request by fdupont-redhat**
The state machine is being ported to InfraConversionJob.
This PR is the counterpart of ManageIQ/manageiq#19238.

RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1747927
Depends on ManageIQ/manageiq#19238
Built on #570

### CODE REVIEW

**Comment by fdupont-redhat** [comment]
@miq-bot add-label transformation, refactoring, ivanchuk/yes
@miq-bot add-reviewer @gmcculloug
@miq-bot add-reviewer @tinaafitz

**Comment by fdupont-redhat** [comment]
Dependent PR has been merged.

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit 5e138d614eb8dca7ba971467fd88c9c70ea0f706
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Wed Sep 11 09:48:20 2019 -0400

    Merge pull request #572 from fdupont-redhat/v2v_state_machine_apply_right_size
    
    [V2] Remove ApplyRightSize state
    
    (cherry picked from commit a69dc82f07b0e3b8692c668557f2474e5357c4a8)
    
    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1768522
```

**Comment by simaishi** [comment]
The backport reverted

```
commit f22b28cdd6b055f05d6e2f808ff604e29522103e
Author: Satoe Imaishi <simaishi@redhat.com>
Date:   Tue Dec 3 11:12:07 2019 -0500

    Revert "Merge pull request #572 from fdupont-redhat/v2v_state_machine_apply_right_size"

    This reverts commit 5e138d614eb8dca7ba971467fd88c9c70ea0f706.

    https://bugzilla.redhat.com/show_bug.cgi?id=1768522
```

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit 421788a5517b52484cf147e1f203cf88b3bcef1b
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Wed Sep 11 09:48:20 2019 -0400

    Merge pull request #572 from fdupont-redhat/v2v_state_machine_apply_right_size

    [V2] Remove ApplyRightSize state

    (cherry picked from commit a69dc82f07b0e3b8692c668557f2474e5357c4a8)

    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1768522
```

**Pull request merged**
