### PR TITLE
Force full refresh for router based events

### PR DESCRIPTION
**Pull request by Ladas**
Force full refresh for router based events. We are not able to
do targeted refresh for routers, until we have changes that will
land for h-release

Fixes BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=1518826

### CODE REVIEW

**Comment by Ladas** [comment]
@miq-bot assign @gmcculloug 
@miq-bot add_label bug

cc @blomquisg @bronaghs

**Comment by gmcculloug** [comment]
@lfu Please review

**Comment by lfu** [comment]
LGTM 👍

**Comment by simaishi** [comment]
`gaprindashvili/yes` ?

**Comment by Ladas** [comment]
@miq-bot add_label gaprindashvili/yes

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit 3187e46b76445db66cb1ecacb554890cadef31b6
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Mon Dec 4 11:07:41 2017 -0500

    Merge pull request #224 from Ladas/force_full_refresh_for_amazon_router_events
    
    Force full refresh for router based events
    (cherry picked from commit 8b57e3a733766f8d0fb951fb34954f2fd95188f3)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1520973
```

**Comment by chrispy1** [comment]
@miq-bot add_label fine/yes

**Comment by simaishi** [comment]
@Ladas @gmcculloug Looks like this depends on https://github.com/ManageIQ/manageiq-content/pull/217. Can this PR and PR 217 go to `fine` branch?

**Comment by Ladas** [comment]
@simaishi hello, yeah, it depends on https://github.com/ManageIQ/manageiq-content/pull/217, so if we would want to backport to Fine, we would have to do a special Fine PR, with the correct refresh actions.

**Pull request merged**
