### PR TITLE
Changed ae_retry_limit = 1.minute to ae_retry_interval = 1.minute.

### PR DESCRIPTION
**Pull request by billfitzgerald0120**
Changes made in Wait_for_ip and Wait_for_completion methods in
ConfigurationManagement namespace.

https://bugzilla.redhat.com/show_bug.cgi?id=1474748

@miq-bot add_label bug, fine/yes, euwe/yes
@miq-bot assign @gmcculloug

### CODE REVIEW

**Comment by billfitzgerald0120** [comment]
@tinaafitz 
Please Review

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit d73d6ad139976ac1777706962f92b0091fd21897
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Tue Jul 25 17:23:48 2017 -0400

    Merge pull request #151 from billfitzgerald0120/fix_ae_retry_interval
    
    Changed ae_retry_limit = 1.minute to ae_retry_interval = 1.minute.
    (cherry picked from commit 0ee9bd467697aed5cc92f85f1210b4ceed73a87a)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1479409
```

**Comment by psachin** [comment]
@billfitzgerald0120 

I see **ConfigurationManagement** is deprecated and **AutomationManagement** takes over. But **AutomationManagement** still has `ae_retry_limit`. Are you going to change that too?

**Comment by gmcculloug** [comment]
@psachin That namespace was updated in PR https://github.com/ManageIQ/manageiq-content/pull/152.

**Comment by psachin** [comment]
@gmcculloug Thanks for the info

**Comment by simaishi** [comment]
Euwe backport (to manageiq repo) details:

```
$ git log -1
commit 78619b5e97e9c294e6506d078fb4dcda9dc5c323
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Tue Jul 25 17:23:48 2017 -0400

    Merge pull request #151 from billfitzgerald0120/fix_ae_retry_interval
    
    Changed ae_retry_limit = 1.minute to ae_retry_interval = 1.minute.
    (cherry picked from commit 0ee9bd467697aed5cc92f85f1210b4ceed73a87a)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1479410
```

**Pull request merged**
