### PR TITLE
Add more aws event handlers

### PR DESCRIPTION
**Pull request by Ladas**
Add more aws event handlers

Partially fixes:
https://bugzilla.redhat.com/show_bug.cgi?id=1511621

### CODE REVIEW

**Comment by Ladas** [comment]
@miq-bot assign bug

**Comment by Ladas** [comment]
@miq-bot add_label bug

**Comment by gmcculloug** [comment]
@Ladas Looks good.  Is this needed in Gaprindashvili?  If so please add the `gaprindashvili/yes` label.

**Comment by Ladas** [comment]
@miq-bot add_label gaprindashvili/yes

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit 101f05f55f5831b0b66de24fe02d364b730df587
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Thu Nov 16 10:51:31 2017 -0500

    Merge pull request #217 from Ladas/add_more_aws_event_handlers
    
    Add more aws event handlers
    (cherry picked from commit bba2391ced0fe83cee347ac2b879446852ffb9a4)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1514270
```

**Pull request merged**
