### PR TITLE
Automate - Refactoring Enhanced Messaging methods.

### PR DESCRIPTION
**Pull request by billfitzgerald0120**
Changed all  {updated_message  += "?"} to {updated_message << "?"}  in all 10 methods.

### CODE REVIEW

**Comment by billfitzgerald0120** [comment]
@tinaafitz 
Please Review

**Comment by tinaafitz** [comment]
@billfitzgerald0120 Looks good.
@mkanoor Please review.

**Comment by billfitzgerald0120** [comment]
@tinaafitz @mkanoor 
this PR should wait till this refactored one gets merged.
#19

**Comment by billfitzgerald0120** [comment]
@tinaafitz 
Please Review

**Comment by gmcculloug** [comment]
@billfitzgerald0120 Lots of rubocop warnings.  Why did you add the `String.new` line instead of keeping the previous logic of initializing the string with the first text message?

**Comment by mkanoor** [comment]
Closed because these changes were done in anticipation of frozen strings in the next version of ruby.
We will make the changes when we get to the next version of ruby.

**Pull request closed without merging**
