### PR TITLE
[Changelog] Update for Hammer-9

### PR DESCRIPTION
**Pull request by JPrause**
[skip ci]

### CODE REVIEW

**Comment by JPrause** [comment]
@miq-bot add_label documentation

**Comment by JPrause** [comment]
@miq-bot add_label hammer/yes

**Comment by JPrause** [comment]
@tinaafitz as time permits, can you review/merge. This is needed for the hammer-9 build.

**Comment by JPrause** [comment]
ping @tinaafitz :arrow_up:

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit 5b010f9ce493face20592f004f14605c2cfc348f
Author: tina <tfitzger@redhat.com>
Date:   Tue Jul 23 08:55:06 2019 -0400

    Merge pull request #550 from JPrause/hammer9_cl
    
    [Changelog] Update for Hammer-9
    
    (cherry picked from commit 80a354575bd7a2beba2383a9c0d5c0207dd54605)
```

**Pull request merged**
