### PR TITLE
Add Azure events for targeted refresh

### PR DESCRIPTION
**Pull request by tumido**
Provide automated refresh on events which are recognized by `event_target_parser` in Azure.

Related to: https://github.com/ManageIQ/manageiq-providers-azure/pull/222

### CODE REVIEW

**Comment by gmcculloug** [comment]
@lfu Please review

**Comment by gmcculloug** [comment]
@tumido Any reason to keep the `wip` label?

**Comment by tumido** [comment]
Just checking if the events get propagated correctly.

We have some events which are inconsistent in names e.g.: `publicIPAddresses_delete_EndRequest` and `publicIpAddresses_delete_EndRequest`. So I'm checking if it has any impact. Maybe you can help me? :wink:

Does the `name` field in the YAML has any importance? I know the proper YAML file is located based on downcased matching against `event_type`, so we should be fine at this point. However, I'm uncertain if it can or cannot cause any harm in any step after that...

We can't have multiple files for the same event, which differs in case-sensitive matching, however downcased are the same. (I know this is our mess and we have to clean it, but we can't do so at this point... Because: reasons, lol.)

**Comment by Ladas** [comment]
This is actually Azure's mess, they don't keep consistent resource type across events (event though it's documented correctly). But I am almost sure we pick the handle by the down-cased string, right @gmcculloug @lfu ?

**Comment by tumido** [comment]
So, I've experimentally confirmed, the events are picked up correctly and the refresh lands fine in the `MiqQueue`. Removing wip. Thanks for the patience. We want to be sure what we're doing, before we break things, lol. :four_leaf_clover: 

@miq-bot remove_label wip

**Comment by gmcculloug** [comment]
@tumido Thanks for testing that out.

**Comment by tumido** [comment]
@miq-bot add_label gaprindashvili/yes

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit eee3cc8ece367ff2b878f8ebb6b00d7fec151608
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Thu Mar 15 14:36:09 2018 -0400

    Merge pull request #261 from tumido/azure_events
    
    Add Azure events for targeted refresh
    (cherry picked from commit af63ed2d5c8942985e4389e4960ae0ac3a22c01b)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1558078
```

**Pull request merged**
