### PR TITLE
[Changelog] Update for Hammer-2

### PR DESCRIPTION
**Pull request by JPrause**
[skip ci]

### CODE REVIEW

**Comment by JPrause** [comment]
@miq-bot add_label documentation

**Comment by JPrause** [comment]
@miq-bot add_label hammer/yes

**Comment by JPrause** [comment]
For backport to Hammer branch
@miq-bot assign simaishi

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit 31e63898c22aca05c78f9c3c294ff18d848717d6
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Thu Jan 31 15:03:13 2019 -0500

    Merge pull request #505 from JPrause/hammer2_cl
    
    [Changelog] Update for Hammer-2
    
    (cherry picked from commit 6fde7701cfc059a7d87f3c1858044c4acecfb1fb)
```

**Pull request merged**
