### PR TITLE
[Changelog] Update for Hammer-6

### PR DESCRIPTION
**Pull request by JPrause**
[skip ci]

### CODE REVIEW

**Comment by JPrause** [comment]
@miq-bot add_label documentation

**Comment by JPrause** [comment]
@miq-bot add_label hammer/yes

**Comment by JPrause** [comment]
@tinaafitz as time permits, can you review/merge.

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit f531d968f5252ea8eefe0ec250975044707c42c6
Author: tina <tfitzger@redhat.com>
Date:   Fri May 17 10:19:36 2019 -0400

    Merge pull request #536 from JPrause/hammer6_cl
    
    [Changelog] Update for Hammer-6
    
    (cherry picked from commit d67fa158ae75039b8c5009befbc7c6b1432d7a98)
```

**Pull request merged**
