### PR TITLE
Change errors in log to error type.

### PR DESCRIPTION
**Pull request by billfitzgerald0120**
Some error messages in log were type info.

https://bugzilla.redhat.com/show_bug.cgi?id=1383732

@miq-bot add_label bug, fine/yes

### CODE REVIEW

**Comment by billfitzgerald0120** [comment]
@miq-bot add_label euwe/yes

**Comment by billfitzgerald0120** [comment]
@tinaafitz 
Please review

**Comment by simaishi** [comment]
Cherry-picked for 2 files that exist in Euwe branch
* `ConfigurationManagement/AnsibleTower/Service/Provisioning/StateMachines/Provision.class/__methods__/check_provisioned.rb`
* `Deployment/ContainerProvider/System/StateMachine/Deployment.class/__methods__/provision.rb`

Euwe backport (to manageiq repo) details:

```
$ git log -1
commit b615b755b364893038bdfa9cac9ff89be6facbcc
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Wed Apr 26 08:50:12 2017 -0400

    Merge pull request #101 from billfitzgerald0120/log_cleanup1
    
    Change errors in log to error type.
    (cherry picked from commit 4bf53776c5f87096502faf60d335f34883f48cdf)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1450214
```

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit fe6ccb57ab74e6dd7f78c2ae891978672fdae4ca
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Wed Apr 26 08:50:12 2017 -0400

    Merge pull request #101 from billfitzgerald0120/log_cleanup1
    
    Change errors in log to error type.
    (cherry picked from commit 4bf53776c5f87096502faf60d335f34883f48cdf)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1459243
```

**Pull request merged**
