### PR TITLE
Remove Hawkular artifacts from miq domain in the automate model

### PR DESCRIPTION
**Pull request by israel-hdez**
Removing Hawkular from Automate.

Per BZ https://bugzilla.redhat.com/show_bug.cgi?id=1526791

image

### CODE REVIEW

**Comment by israel-hdez** [comment]
@miq-bot gaprindashvili/yes, cleanup, providers/middleware

**Comment by israel-hdez** [comment]
ping @abonas @cfcosta

**Comment by israel-hdez** [comment]
@miq-bot add_label gaprindashvili/yes, cleanup, providers/middleware

**Comment by abonas** [comment]
@tumido @cfcosta please review

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit fc0fac97364fefb4565c8eed3f3269b010ab380d
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Tue Jan 2 16:25:43 2018 -0500

    Merge pull request #234 from israel-hdez/remove_hawkular
    
    Remove Hawkular artifacts from miq domain in the automate model
    (cherry picked from commit 4da725cf1c3ae112c81e4bb87f3435045e462025)
```

**Pull request merged**
