### PR TITLE
RBAC filtered results are requiring a get_timezone lookup

### PR DESCRIPTION
**Pull request by syncrou**

### CODE REVIEW

**Comment by syncrou** [comment]
@miq-bot assign @gmcculloug 

@miq-bot add_label bug

**Comment by syncrou** [comment]
@miq-bot remove_label bug

@miq-bot add_label test

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit 556803d34b9b4435094beeff50338e508843bf1a
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Tue Jan 9 13:50:44 2018 -0500

    Merge pull request #238 from syncrou/add_allow_for_rbac
    
    RBAC filtered results are requiring a get_timezone lookup
    (cherry picked from commit 6c95683230b779d5534f213c5635aa2ae827cc5d)
```

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit c92e6ae0cdc214514a3f48bbe60c5c249ef972f9
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Tue Jan 9 13:50:44 2018 -0500

    Merge pull request #238 from syncrou/add_allow_for_rbac
    
    RBAC filtered results are requiring a get_timezone lookup
    (cherry picked from commit 6c95683230b779d5534f213c5635aa2ae827cc5d)
```

**Pull request merged**
