### PR TITLE
Add basic events handlers for AWS

### PR DESCRIPTION
**Pull request by Ladas**
Add basic events handlers for AWS, containing events from
AWS Config, CloudWatch EC2 and CloudWatch with CloudTrail for
API call events.

### CODE REVIEW

**Comment by gmcculloug** [comment]
@Ladas Does this completely supersede  https://github.com/ManageIQ/manageiq-content/pull/180?

cc @lfu

**Comment by Ladas** [comment]
@gmcculloug not completely, these are events I recorded doing operations from MIQ and aws console, but the list is not complete

**Comment by lfu** [comment]
LGTM 👍

**Comment by bronaghs** [comment]
@gmcculloug  - Ready to merge?

**Comment by gmcculloug** [comment]
Yes, all good, I'll merge.

**Pull request merged**
