### PR TITLE
Remove truncate from user message in multiple methods.

### PR DESCRIPTION
**Pull request by billfitzgerald0120**
Truncate is no longer needed.

https://www.pivotaltracker.com/story/show/144129019

@miq-bot add_label cleanup, fine/yes, refactoring

### CODE REVIEW

**Comment by tinaafitz** [comment]
@billfitzgerald0120 Looks good.
@mkanoor Please review.

**Comment by mkanoor** [comment]
@billfitzgerald0120 @tinaafitz 
Is this being done because the model method now does the truncation?
https://github.com/ManageIQ/manageiq/blob/master/app/models/mixins/miq_request_mixin.rb#L17

**Comment by billfitzgerald0120** [comment]
@mkanoor 
Yes

**Comment by simaishi** [comment]
@billfitzgerald0120 @mkanoor Is there a BZ associated with this change? Need a BZ to backport to Fine.

**Pull request merged**
