### PR TITLE
[Changelog] Update for Ivanchuk Beta1

### PR DESCRIPTION
**Pull request by JPrause**
[skip ci]

### CODE REVIEW

**Comment by JPrause** [comment]
@miq-bot add_label documentation

**Comment by JPrause** [comment]
@miq-bot add_label ivanchuk/yes

**Comment by JPrause** [comment]
@tinaafitz as time permits, can you review/merge.

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit aebef02eb72e1d77a699f33146cea31fa25a4a83
Author: tina <tfitzger@redhat.com>
Date:   Wed Jul 31 15:29:21 2019 -0400

    Merge pull request #554 from JPrause/ivanb1_cl
    
    [Changelog] Update for Ivanchuk Beta1
    
    (cherry picked from commit 6dea223fdf38d0b0c32b769b4f6727e1b877e99b)
```

**Pull request merged**
