### PR TITLE
Updated spec dialog parser

### PR DESCRIPTION
**Pull request by mkanoor**
Description from original PR:
This adds support for parsing generic service dialog elements that have multi-select option enabled. This also fixes parsing option service dialog elements that are multi-select and not a VMDB object.

This PR address https://bugzilla.redhat.com/show_bug.cgi?id=1459344
I think this PR should be back ported to Fine and Gaprindashvili.

Additional description:
Added spec for dialog_parser
Based on PR https://github.com/ManageIQ/manageiq-content/pull/253

### CODE REVIEW

**Comment by mkanoor** [comment]
@gmcculloug @tinaafitz 
Please review, just added specs.

**Comment by branic** [comment]
@gmcculloug is this good to be merged?

**Comment by gmcculloug** [comment]
@branic It would help if you could provide some examples of the values being parsed and the resulting values that would be passed down to the tasks.  Not easy to see from the code changes and would be helpful for future reference.

**Comment by branic** [comment]
@gmcculloug here is the example of the values being parsed before and after the change.


Order a Catalog Item with a dialog that has multi-select elements such as:

image

**Before:** dialog_parser couldn't parse any of the non-tag multi-select dialog elements. Notice that although they appear in `dialog_options` they are not in `parsed_dialog_options`. Even though the `test_drop_2` element is included in `parsed_dialog_options` the values selected by the user are not. Child tasks will not have the options set as they are not part of `parsed_dialog_options`.

```
<AEMethod dialog_parser> dialog_options: {"Array::dialog_test_dropdown"=>"1,3", "Array::dialog_option_0_test_drop_2"=>"6,5", "Array::dialog_tag_0_department"=>"Classification::41,Classification::43,Classification::45", "Array::dialog_tag_0_environment"=>"Classification::22", "request"=>"clone_to_service", :service_action=>"Provision", "Service::Service"=>4}
<AEMethod dialog_parser> Current task has dialog information
<AEMethod dialog_parser> parsed_dialog_options: "---\n0:\n  :test_drop_2: []\n"
<AEMethod dialog_parser> parsed_dialog_tags: "---\n0:\n  :department:\n  - accounting\n  - communication\n  - engineering\n  :environment:\n  - prod\n"
```


**After:** dialog_parser can parse all types of multi-select dialog elements. Notice that `parsed_dialog_options` now contains all the non-tag elements and their selected values. Child tasks will have the options set as they are part of `parsed_dialog_options`.

```
<AEMethod dialog_parser> dialog_options: {"Array::dialog_test_dropdown"=>"1,3", "Array::dialog_option_0_test_drop_2"=>"6,5", "Array::dialog_tag_0_department"=>"Classification::41,Classification::43,Classification::45", "Array::dialog_tag_0_environment"=>"Classification::22", "request"=>"clone_to_service", :service_action=>"Provision", "Service::Service"=>5}
<AEMethod dialog_parser> Current task has dialog information
<AEMethod dialog_parser> parsed_dialog_options: "---\n0:\n  :test_dropdown:\n  - '1'\n  - '3'\n  :dialog_test_dropdown:\n  - '1'\n  - '3'\n  :test_drop_2:\n  - '6'\n  - '5'\n"
<AEMethod dialog_parser> parsed_dialog_tags: "---\n0:\n  :department:\n  - accounting\n  - communication\n  - engineering\n  :environment:\n  - prod\n"
```

**Pull request merged**
