### PR TITLE
[WIP] Adding alert instances and methods for Email.

### PR DESCRIPTION
**Pull request by billfitzgerald0120**
Adding 6 new instances to System/Notification/Email class.

Original instances/methods came from Control/Email.

https://bugzilla.redhat.com/show_bug.cgi?id=1314871

https://www.pivotaltracker.com/epic/show/3861726

### CODE REVIEW

**Comment by billfitzgerald0120** [comment]
@miq-bot add_label enhancement

**Comment by billfitzgerald0120** [comment]
@tinaafitz Please Review

**Comment by tinaafitz** [comment]
@billfitzgerald0120 Looks good.
@mkanoor Please review.

**Comment by billfitzgerald0120** [comment]
Closed in favor of https://github.com/ManageIQ/manageiq-content/pull/322

**Pull request closed without merging**
