### PR TITLE
[V2V] Remove PreMigration Ansible playbook

### PR DESCRIPTION
**Pull request by fdupont-redhat**
The state machine is being ported to InfraConversionJob.
This PR is the counterpart of ManageIQ/manageiq#19200.

RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1740881
Depends on ManageIQ/manageiq#19200
Built on #566

### CODE REVIEW

**Comment by fdupont-redhat** [comment]
@miq-bot add-label transformation, refactoring, ivanchuk/yes
@miq-bot add-reviewer @gmcculloug
@miq-bot add-reviewer @tinaafitz

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit 26def1da17f6609d95c10ee4a89bcf70b29c9c0e
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Thu Aug 29 07:02:55 2019 -0400

    Merge pull request #567 from fdupont-redhat/v2v_state_machine_remove_pre_migration_ansible_playbook
    
    [V2V] Remove PreMigration Ansible playbook
    
    (cherry picked from commit 35fae0c6b5af0dafb9d2a0b1239e03c55b94a456)
    
    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1767638
```

**Comment by simaishi** [comment]
The backport reverted

```
commit bf4f2de7863f51f896b2445cb5eba47c8649be43
Author: Satoe Imaishi <simaishi@redhat.com>
Date:   Tue Dec 3 11:13:16 2019 -0500

    Revert "Merge pull request #567 from fdupont-redhat/v2v_state_machine_remove_pre_migration_ansible_playbook"

    This reverts commit 26def1da17f6609d95c10ee4a89bcf70b29c9c0e.

    https://bugzilla.redhat.com/show_bug.cgi?id=1767638
```

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit 04de657b29d0b5bbea2c108164a4e90a8990b157
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Thu Aug 29 07:02:55 2019 -0400

    Merge pull request #567 from fdupont-redhat/v2v_state_machine_remove_pre_migration_ansible_playbook

    [V2V] Remove PreMigration Ansible playbook

    (cherry picked from commit 35fae0c6b5af0dafb9d2a0b1239e03c55b94a456)

    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1767638
```

**Pull request merged**
