### PR TITLE
make order_ansible_playbook use floating ip address first if available

### PR DESCRIPTION
**Pull request by ramrexx**

### CODE REVIEW

**Comment by gmcculloug** [comment]
@ramrexx Can you add a test for this change here (https://github.com/ManageIQ/manageiq-content/blob/master/spec/content/automate/ManageIQ/System/Request.class/__methods__/order_ansible_playbook_spec.rb).

Let us know if you need some help with this.

**Comment by ramrexx** [comment]
@gmcculloug - yes i could use some guidance for this as I have never written a test before.

**Comment by gmcculloug** [comment]
@ramrexx This is not a straightforward as I would have hoped since most of the methods here are private.  I was playing around with some updates to the spec and I'll post back here when I have something.

**Comment by gmcculloug** [comment]
@ramrexx I realized this was built on the `master` branch instead of creating a feature branch for these change.  To fix that and to include my test changes I created a new branch and cherry-picked your commit to it.

Closing in favor of https://github.com/ManageIQ/manageiq-content/pull/195.

**Pull request closed without merging**
