### PR TITLE
Automate - Notification for Ansible and Cloud provisioning errors.

### PR DESCRIPTION
**Pull request by billfitzgerald0120**
This sends a notification with an error occurs.

Modified update_serviceprovision_status methods in
Cloud/Orchestration/Provisioning/StateMachines/Provision/ and
ConfigurationManagement/AnsibleTower/Service/Provisioning/StateMachines/Provision
Methods class.

Updated existing spec to test for notification in case of error.

### CODE REVIEW

**Comment by billfitzgerald0120** [comment]
@tinaafitz 
Please review

**Comment by tinaafitz** [comment]
@billfitzgerald0120 Looks good.
@mkanoor Please review.

**Comment by mkanoor** [comment]
@billfitzgerald0120 @tinaafitz 

Can this PR wait till this refactored one gets merged.
https://github.com/ManageIQ/manageiq-content/pull/19

**Comment by billfitzgerald0120** [comment]
@mkanoor 
Yes

**Comment by billfitzgerald0120** [comment]
@tinaafitz 
Please review

**Comment by billfitzgerald0120** [comment]
@tinaafitz 
Please Review

**Comment by tinaafitz** [comment]
@billfitzgerald0120 Looks good.
@mkanoor Please review.

**Comment by billfitzgerald0120** [comment]
@miq-bot add-label enhancement

**Comment by mkanoor** [comment]
@billfitzgerald0120 
Do we need these changes here too
https://github.com/ManageIQ/manageiq-content/blob/master/content/automate/ManageIQ/AutomationManagement/AnsibleTower/Service/Provisioning/StateMachines/Provision.class/__methods__/update_serviceprovision_status.rb#L25

**Comment by billfitzgerald0120** [comment]
@mkanoor Please review.

**Comment by gmcculloug** [comment]
@mkanoor Can this be merged?  Please label `fine/yes` or `fine/no`

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit 70abcc2818ea1451f6c612c5985c0fe781cb7dcc
Author: Madhu Kanoor <mkanoor@redhat.com>
Date:   Thu Mar 30 17:39:37 2017 -0400

    Merge pull request #15 from billfitzgerald0120/cnotify_ansible
    
    Automate - Notification for Ansible and Cloud provisioning errors.
    (cherry picked from commit ee6b46b928d44d994b89ff273abe31d186cccffc)
```

**Pull request merged**
