### PR TITLE
manageiq-core.manageiq-automate Wrap all values in quotes

### PR DESCRIPTION
**Pull request by syncrou**
Reworks the exists() method to wrap all values in quotes so
the bool() method will not interpret the values as false.

This change brings the shipped role / module in line with release 0.1.1 on [Galaxy](https://galaxy.ansible.com/syncrou/manageiq-automate)

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1730311

### CODE REVIEW

**Comment by syncrou** [comment]
@miq-bot assign @tinaafitz

**Comment by syncrou** [comment]
@miq-bot add_label bug

**Comment by simaishi** [comment]
@syncrou `ivanchuk/yes`?

**Comment by syncrou** [comment]
@simaishi  Not sure.  @tinaafitz Do you have insight into this question?

**Comment by tinaafitz** [comment]
@syncrou @simaishi Yes for ```ivanchuk/yes```

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit 959321e68f078a91315385acdd25a5d9aea5adb0
Author: tina <tfitzger@redhat.com>
Date:   Fri Aug 2 16:18:42 2019 -0400

    Merge pull request #555 from syncrou/wrap_all_values_in_quotes
    
    manageiq-core.manageiq-automate Wrap all values in quotes
    
    (cherry picked from commit f0bf90e63d9baa19c9392995b73b99cd0223f0cd)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1730311
```

**Pull request merged**
