### PR TITLE
Changelog 63

### PR DESCRIPTION
**Pull request by mfeifer**
3 PRS

[skip ci]

### CODE REVIEW

**Comment by mfeifer** [comment]
@miq-bot add_label wip

**Comment by mfeifer** [comment]
@miq-bot add_label documentation

**Comment by mfeifer** [comment]
@miq-bot remove_label wip

**Comment by gmcculloug** [comment]
@mfeifer Can you add PR https://github.com/ManageIQ/manageiq-content/pull/127 which was also merged in [Milestone 63](https://github.com/ManageIQ/manageiq-content/milestone/10?closed=1)

**Pull request merged**
