### PR TITLE
Add refresh hook for AWS_API_CALL_ModifyVolume

### PR DESCRIPTION
**Pull request by djberg96**
We have handlers for creating, attaching, detaching and deleting volumes, but none currently for modifying a volume.

Attempts to address https://github.com/ManageIQ/manageiq-providers-amazon/issues/637

### CODE REVIEW

**Comment by lfu** [comment]
@djberg96 Can you address the Travis failure? Thanks.

**Comment by djberg96** [comment]
@lfu How was I supposed to generate this file?

**Comment by lfu** [comment]
@djberg96 Please followe the steps in [Creating a Pull Request for enhancements to ManageIQ Automate Domain?](
http://talk.manageiq.org/t/creating-a-pull-request-for-enhancements-to-manageiq-automate-domain/1041)

**Comment by djberg96** [comment]
@lfu I'm having trouble following these steps. First, I think the original rake task assumes the stuff still lives in core (it's now in manageiq-content). Second, even after just manually copying it over I see a lot of unrelated modifications.

**Comment by djberg96** [comment]
@lfu Looks like it's green now.

**Comment by lfu** [comment]
LGTM

**Comment by simaishi** [comment]
Jansa backport details:

```
$ git log -1
commit 54bcf98b2db68d71643e7af679fb4e7f66fef486
Author: tina <tfitzger@redhat.com>
Date:   Thu Jul 30 07:35:35 2020 -0400

    Merge pull request #663 from djberg96/aws_volume_modify

    Add refresh hook for AWS_API_CALL_ModifyVolume

    (cherry picked from commit 6788b6d1a6daf2d7dca2ced3f8d5bd0ac218415f)
```

**Pull request merged**
