### PR TITLE
Vm retirement is processed by VmRetireRequest state machine.

### PR DESCRIPTION
**Pull request by lfu**
Blocks https://github.com/ManageIQ/manageiq/pull/19064.

https://bugzilla.redhat.com/show_bug.cgi?id=1702018

@miq-bot add_label bug, hammer/yes, ivanchuk/yes, changelog/yes

### CODE REVIEW

**Comment by tinaafitz** [comment]
Prior to 5.11, retirement (using retire_now) was event based. When retire_now was called for VM retirement, a request_vm_retire event would be raised and come through the event policy request_vm_retire instance in this PR.  
The retirement request event instances remain in 5.11, but are not being used.

The code change in this PR removes the unused entries in the request_vm_retire instance, while leaving the necessary policy event check connection.

**Comment by tinaafitz** [comment]
@mkanoor Please review.

**Comment by mkanoor** [comment]
@tinaafitz @lfu 
What would happen if the customers have overridden this instance in their own domain with extra stuff before they do the retirement. Do we need a tech note or something to tell them that their instance needs to be updated.

**Comment by tinaafitz** [comment]
Yes, @mkanoor, that makes sense. I added a doc release note flag to the ticket. We should document any changes to the ManageIQ domain.

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit 8945d950176efb5086ce4537e512a3f04fb90366
Author: Madhu Kanoor <mkanoor@redhat.com>
Date:   Wed Aug 14 17:52:01 2019 -0400

    Merge pull request #552 from lfu/prevent_retirement_1702018

    Vm retirement is processed by VmRetireRequest state machine.

    (cherry picked from commit 3e2fb4beb1c6d214ca62daa65eb9856d6cc69a5c)

    https://bugzilla.redhat.com/show_bug.cgi?id=1783361
```

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit 87cbdb74de606d1d38e927c5f77ba06a036406fa
Author: Madhu Kanoor <mkanoor@redhat.com>
Date:   Wed Aug 14 17:52:01 2019 -0400

    Merge pull request #552 from lfu/prevent_retirement_1702018

    Vm retirement is processed by VmRetireRequest state machine.

    (cherry picked from commit 3e2fb4beb1c6d214ca62daa65eb9856d6cc69a5c)

    https://bugzilla.redhat.com/show_bug.cgi?id=1783360
```

**Pull request merged**
