### PR TITLE
New refresh method callable from the automate

### PR DESCRIPTION
**Pull request by Ladas**
New refresh method callable from the automate, it tries
to call targeted manager refresh if defined, otherwise fallback to
full refresh.

This is needed for invoking https://github.com/ManageIQ/manageiq-automation_engine/blob/master/lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_builtin_method.rb#L101

### CODE REVIEW

**Comment by Ladas** [comment]
@cc @gmcculloug @blomquisg we need this so we can invoke the new targeted refresh from the automate

the usage is just "/System/event_handlers/refresh" and the targets are scanned inside, or the result can be full refresh, if we disable the targeted refresh via settings.

**Comment by gmcculloug** [comment]
@lfu Please review

**Comment by lfu** [comment]
@Ladas Does this refresh method work only for Amazon? Or eventually it will work for all providers?
Would like to know if this is a replacement for ```event_action_refresh``` and ```event_action_refresh_sync```.

**Comment by Ladas** [comment]
@lfu we will use it for targeted refresh of AWS and OpenStack, for 4.6. In other providers, it would just invoke full refresh, because of a missing Settings value.

At some point, it will replace ```event_action_refresh```, but that will take some time. (we will need targeted graph refresh in all providers)

**Comment by lfu** [comment]
Changes LGTM 👍

**Pull request merged**
