### PR TITLE
Moving RedHat domain content for 8 existing methods to ManageIQ.

### PR DESCRIPTION
**Pull request by billfitzgerald0120**
Moving/Replacing 8 RedHat Automate methods to the ManageIQ domain:
  2 for Cloud/Vm/Provisioning/StateMachine/Methods
  6 for Infrastructure/Vm/Provisioning/StateMachine/Methods

These are methods that are currently in the ManageIQ domain.

image

@miq-bot assign @tinaafitz

### CODE REVIEW

**Comment by lfu** [comment]
It looks good. Just wondering if there is any existing tests for these methods.

**Comment by billfitzgerald0120** [comment]
> It looks good. Just wondering if there is any existing tests for these methods.

There are no existing specs.  The replaced methods only had a log message.

**Comment by tinaafitz** [comment]
Hi @pkomanek Can you refactor the 8 methods included in this PR, and add spec tests?

**Comment by pkomanek** [comment]
Hi @tinaafitz. Sure.

**Pull request merged**
