### PR TITLE
Use supports_vm_import? instead of validate_import_vm

### PR DESCRIPTION
**Pull request by smelamud**
Depends-on: 
https://github.com/ManageIQ/manageiq/pull/16526
https://github.com/ManageIQ/manageiq-automation_engine/pull/121

### CODE REVIEW

**Comment by smelamud** [comment]
@miq-bot assign gmcculloug

**Comment by gmcculloug** [comment]
Tested locally with PR https://github.com/ManageIQ/manageiq-automation_engine/pull/121.  Gets travis tests back to green, but travis is not running on this PR.  😦

**Comment by smelamud** [comment]
@miq-bot add_labels gaprindashvili/yes

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit 862cdefc3970a54df632e21b041ce52e01b7f1be
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Mon Nov 27 22:24:05 2017 -0500

    Merge pull request #218 from smelamud/supports-vm-import
    
    Use supports_vm_import? instead of validate_import_vm
    (cherry picked from commit 5203bb7d0aec521eda423ccb16df0955ee7a9503)
```

**Pull request merged**
