### PR TITLE
Add azure event handlers for targeted refresh

### PR DESCRIPTION
**Pull request by Ladas**
Add azure event handlers for targeted refresh

Partially fixes:
https://bugzilla.redhat.com/show_bug.cgi?id=1487602

### CODE REVIEW

**Comment by Ladas** [comment]
@bronaghs we will need this for the targeted refresh

**Comment by gmcculloug** [comment]
@lfu Please review

**Comment by gmcculloug** [comment]
@Ladas I added the `gaprindashvili/yes` label.  Is this also needed for the `Fine` branch?

**Comment by Ladas** [comment]
gaprindashvili/yes only, we would have to use the old refresh action backporting it further

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit 8b6c90add56b99d012b80fcad6b72d7e818f7a38
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Fri Mar 9 11:00:49 2018 -0500

    Merge pull request #260 from Ladas/add_azure_event_handlers_for_targeted_refresh
    
    Add azure event handlers for targeted refresh
    (cherry picked from commit c189e91a554b21ee86bb7aed76cf110b1568b601)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1558078
```

**Pull request merged**
