### PR TITLE
[V2V] Remove VMTransform and VMCheckTransformed states

### PR DESCRIPTION
**Pull request by fdupont-redhat**
The state machine is being ported to InfraConversionJob.
This PR is the counterpart of ManageIQ/manageiq#19222.

RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1746592
Depends on ManageIQ/manageiq#19222
Built on #568

### CODE REVIEW

**Comment by fdupont-redhat** [comment]
@miq-bot add-label transformation, refactoring, ivanchuk/yes
@miq-bot add-reviewer @gmcculloug
@miq-bot add-reviewer @tinaafitz

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit 35cf51360efe3659a142dc124866cc099487e8dc
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Mon Sep 2 12:17:29 2019 -0400

    Merge pull request #569 from fdupont-redhat/v2v_state_machine_transform_vm
    
    [V2V] Remove VMTransform and VMCheckTransformed states
    
    (cherry picked from commit 3b0e6b2fd0176e894d07df24b95203f696b65f32)
    
    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1767542
```

**Comment by simaishi** [comment]
The backport reverted

```
commit 1c76cd29d3f46017ef62310a654673b4a2cdaae0
Author: Satoe Imaishi <simaishi@redhat.com>
Date:   Tue Dec 3 11:12:42 2019 -0500

    Revert "Merge pull request #569 from fdupont-redhat/v2v_state_machine_transform_vm"

    This reverts commit 35cf51360efe3659a142dc124866cc099487e8dc.

    https://bugzilla.redhat.com/show_bug.cgi?id=1767542
```

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit ee6ec2c0b95336d55abcba89ef4827459151f879
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Mon Sep 2 12:17:29 2019 -0400

    Merge pull request #569 from fdupont-redhat/v2v_state_machine_transform_vm

    [V2V] Remove VMTransform and VMCheckTransformed states

    (cherry picked from commit 3b0e6b2fd0176e894d07df24b95203f696b65f32)

    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1767542
```

**Pull request merged**
