### PR TITLE
Modified microsoft_best_fit_least_utilized to not select Hosts in mai…

### PR DESCRIPTION
**Pull request by billfitzgerald0120**
…ntenance.

Added test for maintenance mode check.

See BZ for vmware : https://bugzilla.redhat.com/show_bug.cgi?id=1434025

See PR for vmware : https://github.com/ManageIQ/manageiq-content/pull/81

### CODE REVIEW

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit 52ad83d80ad43023577606a5986f18db219f5932
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Fri Mar 31 11:57:30 2017 -0400

    Merge pull request #84 from billfitzgerald0120/best_fit_host_maint_check_for_microsoft
    
    Modified microsoft_best_fit_least_utilized to not select Hosts in mai…
    (cherry picked from commit d30259e2db0ba1de4bb96b2e6d9373ac12177533)
```

**Comment by simaishi** [comment]
@billfitzgerald0120 is there a BZ for this PR?

**Comment by billfitzgerald0120** [comment]
There isn't a separate BZ for this one.   Do you want me to create a new BZ for this one ?

**Comment by billfitzgerald0120** [comment]
I created a BZ for this.  https://bugzilla.redhat.com/show_bug.cgi?id=1452820

**Comment by simaishi** [comment]
Euwe backport (to manageiq repo) details:

```
$ git log -1
commit 47d5fdaf96f632385bf4da7d6e7f61420da228b0
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Fri Mar 31 11:57:30 2017 -0400

    Merge pull request #84 from billfitzgerald0120/best_fit_host_maint_check_for_microsoft
    
    Modified microsoft_best_fit_least_utilized to not select Hosts in mai…
    (cherry picked from commit d30259e2db0ba1de4bb96b2e6d9373ac12177533)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1452824
```

**Pull request merged**
