### PR TITLE
[V2V] Remove PowerOff state

### PR DESCRIPTION
**Pull request by fdupont-redhat**
The state machine is being ported to InfraConversionJob.
This PR is the counterpart of ManageIQ/manageiq#19216.

A side effect of removing the PowerOff method, is that the PreTransform state machine is not needed anymore. So, the PR removes it too.

RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1746365
Depends on ManageIQ/manageiq#19216
Built on #567

### CODE REVIEW

**Comment by fdupont-redhat** [comment]
@miq-bot add-label transformation, refactoring, ivanchuk/yes
@miq-bot add-reviewer @gmcculloug
@miq-bot add-reviewer @tinaafitz

**Comment by fdupont-redhat** [comment]
@miq-bot add-label transformation, refactoring, ivanchuk/yes
@miq-bot add-reviewer @gmcculloug
@miq-bot add-reviewer @tinaafitz

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit 1f4748a522a81d77ceb4d9800e85c81e3efb3b5e
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Mon Sep 2 12:17:09 2019 -0400

    Merge pull request #568 from fdupont-redhat/v2v_state_machine_shutdown
    
    [V2V] Remove PowerOff state
    
    (cherry picked from commit 0f27ca73bc188f5390edaf7047c992cc4417f3b5)
    
    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1767545
```

**Comment by simaishi** [comment]
The backport reverted

```
commit 913b4fe437777abe6f117c960b9f3f922a3b4b2e
Author: Satoe Imaishi <simaishi@redhat.com>
Date:   Tue Dec 3 11:13:01 2019 -0500

    Revert "Merge pull request #568 from fdupont-redhat/v2v_state_machine_shutdown"

    This reverts commit 1f4748a522a81d77ceb4d9800e85c81e3efb3b5e.

    https://bugzilla.redhat.com/show_bug.cgi?id=1767545
```

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit 3e9a1fdec69f4643fc99a83be35411f10db16a91
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Mon Sep 2 12:17:09 2019 -0400

    Merge pull request #568 from fdupont-redhat/v2v_state_machine_shutdown

    [V2V] Remove PowerOff state

    (cherry picked from commit 0f27ca73bc188f5390edaf7047c992cc4417f3b5)

    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1767545
```

**Pull request merged**
