### PR TITLE
Refactor used quota method and test.

### PR DESCRIPTION
**Pull request by billfitzgerald0120**
This PR is based on on the issue below.
https://github.com/ManageIQ/manageiq/issues/12038

@miq-bot add_label refactoring

### CODE REVIEW

**Comment by billfitzgerald0120** [comment]
@miq-bot assign @gmcculloug

**Comment by billfitzgerald0120** [comment]
@tinaafitz Please Review

**Comment by billfitzgerald0120** [comment]
@tinaafitz Made changes as requested, Please Review

**Comment by billfitzgerald0120** [comment]
@miq-bot add_label fine/yes

**Comment by simaishi** [comment]
@billfitzgerald0120 Is there a BZ for this issue?

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit 137152446e08d45ccaaf326715e95cae169603f8
Author: Madhu Kanoor <mkanoor@redhat.com>
Date:   Thu Oct 5 09:59:18 2017 -0400

    Merge pull request #191 from billfitzgerald0120/used_active_provisions
    
    Refactor used quota method and test.
    (cherry picked from commit 5cc73ae823ff9ec8ec3bf2c4253cb8f416a25fc8)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1489507
```

**Pull request merged**
