### PR TITLE
New email consolidated namespace and class.

### PR DESCRIPTION
**Pull request by billfitzgerald0120**
This PR will build the new email namespace and class so that new development and projects like v2v
can take advantage of the new functionality included.

/System/Notification/Email class and schema with default values will be built.

This is just a subset of PR: https://github.com/ManageIQ/manageiq-content/pull/18

### CODE REVIEW

**Comment by billfitzgerald0120** [comment]
@tinaafitz Please Review

**Comment by lfu** [comment]
LGTM

**Comment by simaishi** [comment]
@billfitzgerald0120 Please add BZ link.

**Comment by billfitzgerald0120** [comment]
@simaishi I created this BZ.  Sorry it took so long.   Thanks
https://bugzilla.redhat.com/show_bug.cgi?id=1553936

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit 1d5eeb5f392763003a3d3d5eed2b8a880de9a4bc
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Wed Feb 7 15:35:15 2018 -0500

    Merge pull request #246 from billfitzgerald0120/new_email_class
    
    New email consolidated namespace and class.
    (cherry picked from commit ea735764bfc5ebcd1e090f7c30090908e74124a2)
    
    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1583846
```

**Comment by kedark3** [comment]
@billfitzgerald0120 could you please provide me a way to test this?
 https://bugzilla.redhat.com/show_bug.cgi?id=1584695

**Comment by gmcculloug** [comment]
@kedark3 Are you asking how to test the content of the PR or the BZ you linked?  I'm confused 😕

**Comment by kedark3** [comment]
@gmcculloug yes, I meant way to validate BZ associated with it.

**Pull request merged**
