### PR TITLE
[V2V] Remove CollapseSnapshots state and methods

### PR DESCRIPTION
**Pull request by fdupont-redhat**
The state machine is being ported to InfraConversionJob.
This PR is the counterpart of https://github.com/ManageIQ/manageiq/pull/19177.

RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1740881
Depends on https://github.com/ManageIQ/manageiq/pull/19177

### CODE REVIEW

**Comment by fdupont-redhat** [comment]
@miq-bot add-label transformation, refactoring, ivanchuk/yes
@miq-bot add-reviewer @gmcculloug

**Comment by fdupont-redhat** [comment]
@miq-bot add-reviewer @tinaafitz

**Comment by djberg96** [comment]
:+1:

**Comment by fdupont-redhat** [comment]
@gmcculloug the dependent PR is merged. Thanks.

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit f8d1c45aff1132f2b10daa7b84c9afe802001c22
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Thu Aug 29 07:02:14 2019 -0400

    Merge pull request #566 from fdupont-redhat/v2v_state_machine_remove_collapse_snapshots
    
    [V2V] Remove CollapseSnapshots state and methods
    
    (cherry picked from commit 2e96f80c70aecb5f9f85d39a04f74ff59acd4860)
    
    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1767543
```

**Comment by simaishi** [comment]
The backport reverted

```
commit ef852cadf851d2835424c46ccf8db2fef62e2074
Author: Satoe Imaishi <simaishi@redhat.com>
Date:   Tue Dec 3 11:13:32 2019 -0500

    Revert "Merge pull request #566 from fdupont-redhat/v2v_state_machine_remove_collapse_snapshots"

    This reverts commit f8d1c45aff1132f2b10daa7b84c9afe802001c22.

    https://bugzilla.redhat.com/show_bug.cgi?id=1767543
```

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit 702e072fccbbb44ae6d6c0de1254bf62a6f3bc4a
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Thu Aug 29 07:02:14 2019 -0400

    Merge pull request #566 from fdupont-redhat/v2v_state_machine_remove_collapse_snapshots

    [V2V] Remove CollapseSnapshots state and methods

    (cherry picked from commit 2e96f80c70aecb5f9f85d39a04f74ff59acd4860)

    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1767543
```

**Pull request merged**
