### PR TITLE
Support embedded_ansible to fetch credentials from provider

### PR DESCRIPTION
**Pull request by mkanoor**
https://bugzilla.redhat.com/show_bug.cgi?id=1448918

If we dont find a ansible provider thru the service template and
the method gets passed in a parameter embedded_ansible true we use
the first Embedded Ansible Provider and collect the credentials
connected to it

### CODE REVIEW

**Comment by mkanoor** [comment]
@bzwei @tinaafitz @gmcculloug 
Please review

**Comment by chrispy1** [comment]
@miq-bot add_label blocker

**Comment by bzwei** [comment]
LGTM

**Comment by tinaafitz** [comment]
@mkanoor Looks good.

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit 2ce9007026cbf04e87b30089a3784199fc8569ad
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Tue May 9 12:27:07 2017 -0400

    Merge pull request #112 from mkanoor/bz_1448918
    
    Support embedded_ansible to fetch credentials from provider
    (cherry picked from commit 519518a27bf69ed70de269cff1cd68a22e95a4d7)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1449366
```

**Pull request merged**
