### PR TITLE
[V2V] Remove CheckVmInInventory state

### PR DESCRIPTION
**Pull request by fdupont-redhat**
The state machine is being ported to InfraConversionJob.
This PR is the counterpart of ManageIQ/manageiq#19230.

A side effect of removing the CheckVmInInventory method, is that the Transform state machine is not needed anymore. So, the PR removes it too.

RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1747338
Depends on ManageIQ/manageiq#19238
Built on #569

### CODE REVIEW

**Comment by fdupont-redhat** [comment]
@miq-bot add-label transformation, refactoring, ivanchuk/yes
@miq-bot add-reviewer @gmcculloug
@miq-bot add-reviewer @tinaafitz

**Comment by fdupont-redhat** [comment]
Dependent PR was changed to https://github.com/ManageIQ/manageiq/pull/19238, which is merged.

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit 8546669a088faae60522e64c088e7820957c161b
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Wed Sep 11 09:48:06 2019 -0400

    Merge pull request #570 from fdupont-redhat/v2v_state_machine_waiting_for_inventory_refresh
    
    [V2V] Remove CheckVmInInventory state
    
    (cherry picked from commit 32ef3e15f0362b0404505a938df17bc71f2df376)
    
    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1768521
```

**Comment by simaishi** [comment]
The backport reverted

```
commit 7998bd805a1c5779921c9d9ee8d31612d3dce725
Author: Satoe Imaishi <simaishi@redhat.com>
Date:   Tue Dec 3 11:12:24 2019 -0500

    Revert "Merge pull request #570 from fdupont-redhat/v2v_state_machine_waiting_for_inventory_refresh"

    This reverts commit 8546669a088faae60522e64c088e7820957c161b.

    https://bugzilla.redhat.com/show_bug.cgi?id=1768521
```

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit 48d99b990544e23bd7f66209e9c5467bc0ecc9b5
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Wed Sep 11 09:48:06 2019 -0400

    Merge pull request #570 from fdupont-redhat/v2v_state_machine_waiting_for_inventory_refresh

    [V2V] Remove CheckVmInInventory state

    (cherry picked from commit 32ef3e15f0362b0404505a938df17bc71f2df376)

    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1768521
```

**Pull request merged**
